spring:
  application:
    name: transportation-service

  datasource:
    url: jdbc:mysql://localhost:3306/affablebean
    username: root
    password: kyawzayya

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8070